---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[baremetal_machine::default]
    attributes:
